void lep_charge()
{
//=========Macro generated from canvas: lep_charge/title
//=========  (Wed Jul 19 10:23:48 2017) by ROOT version6.08/04
   TCanvas *lep_charge = new TCanvas("lep_charge", "title",0,0,900,900);
   gStyle->SetOptStat(0);
   lep_charge->SetHighLightColor(2);
   lep_charge->Range(0,0,1,1);
   lep_charge->SetFillColor(0);
   lep_charge->SetBorderMode(0);
   lep_charge->SetBorderSize(2);
   lep_charge->SetTickx(1);
   lep_charge->SetTicky(1);
   lep_charge->SetLeftMargin(0.16);
   lep_charge->SetRightMargin(0.05);
   lep_charge->SetBottomMargin(0.16);
   lep_charge->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Main
   TPad *Main = new TPad("Main", "Main",0,0.3,1,1);
   Main->Draw();
   Main->cd();
   Main->Range(-2.458861,-34.39193,1.971519,6843.993);
   Main->SetFillColor(0);
   Main->SetBorderMode(0);
   Main->SetBorderSize(2);
   Main->SetTickx(1);
   Main->SetTicky(1);
   Main->SetLeftMargin(0.16);
   Main->SetRightMargin(0.05);
   Main->SetBottomMargin(0.005);
   Main->SetFrameBorderMode(0);
   Main->SetFrameBorderMode(0);
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("Lepton Charge");
   
   TH1F *_stack_6 = new TH1F("_stack_6","Lepton Charge",7,-1.75,1.75);
   _stack_6->SetMinimum(0);
   _stack_6->SetMaximum(6156.155);
   _stack_6->SetDirectory(0);
   _stack_6->SetStats(0);
   _stack_6->SetMarkerStyle(20);
   _stack_6->GetXaxis()->SetTitle(" Q^{lep}");
   _stack_6->GetXaxis()->SetLabelFont(43);
   _stack_6->GetXaxis()->SetLabelSize(25);
   _stack_6->GetXaxis()->SetTitleSize(25);
   _stack_6->GetXaxis()->SetTitleOffset(2);
   _stack_6->GetXaxis()->SetTitleFont(43);
   _stack_6->GetYaxis()->SetTitle(" Leptons");
   _stack_6->GetYaxis()->SetLabelFont(43);
   _stack_6->GetYaxis()->SetLabelSize(25);
   _stack_6->GetYaxis()->SetTitleSize(25);
   _stack_6->GetYaxis()->SetTitleOffset(2);
   _stack_6->GetYaxis()->SetTitleFont(43);
   _stack_6->GetZaxis()->SetLabelFont(43);
   _stack_6->GetZaxis()->SetLabelSize(25);
   _stack_6->GetZaxis()->SetTitleSize(25);
   _stack_6->GetZaxis()->SetTitleFont(43);
   ->SetHistogram(_stack_6);
   
   
   TH1D *lep_charge__41 = new TH1D("lep_charge__41","Lepton Charge",7,-1.75,1.75);
   lep_charge__41->SetBinContent(2,1.605329);
   lep_charge__41->SetBinContent(6,2.534407);
   lep_charge__41->SetBinError(2,0.1758688);
   lep_charge__41->SetBinError(6,0.2134211);
   lep_charge__41->SetEntries(436);
   lep_charge__41->SetDirectory(0);
   lep_charge__41->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#fa7921");
   lep_charge__41->SetFillColor(ci);
   lep_charge__41->SetMarkerStyle(20);
   lep_charge__41->GetXaxis()->SetTitle(" Q^{lep}");
   lep_charge__41->GetXaxis()->SetLabelFont(43);
   lep_charge__41->GetXaxis()->SetLabelSize(25);
   lep_charge__41->GetXaxis()->SetTitleSize(25);
   lep_charge__41->GetXaxis()->SetTitleOffset(2);
   lep_charge__41->GetXaxis()->SetTitleFont(43);
   lep_charge__41->GetYaxis()->SetTitle(" Leptons");
   lep_charge__41->GetYaxis()->SetLabelFont(43);
   lep_charge__41->GetYaxis()->SetLabelSize(25);
   lep_charge__41->GetYaxis()->SetTitleSize(25);
   lep_charge__41->GetYaxis()->SetTitleOffset(2);
   lep_charge__41->GetYaxis()->SetTitleFont(43);
   lep_charge__41->GetZaxis()->SetLabelFont(43);
   lep_charge__41->GetZaxis()->SetLabelSize(25);
   lep_charge__41->GetZaxis()->SetTitleSize(25);
   lep_charge__41->GetZaxis()->SetTitleFont(43);
   ->Add(lep_charge,"");
   
   TH1D *lep_charge__42 = new TH1D("lep_charge__42","Lepton Charge",7,-1.75,1.75);
   lep_charge__42->SetBinContent(2,2.576606);
   lep_charge__42->SetBinContent(6,2.378422);
   lep_charge__42->SetBinError(2,0.2875258);
   lep_charge__42->SetBinError(6,0.2704747);
   lep_charge__42->SetEntries(269);
   lep_charge__42->SetDirectory(0);
   lep_charge__42->SetStats(0);

   ci = TColor::GetColor("#5bc0eb");
   lep_charge__42->SetFillColor(ci);
   lep_charge__42->SetMarkerStyle(20);
   lep_charge__42->GetXaxis()->SetTitle(" Q^{lep}");
   lep_charge__42->GetXaxis()->SetLabelFont(43);
   lep_charge__42->GetXaxis()->SetLabelSize(25);
   lep_charge__42->GetXaxis()->SetTitleSize(25);
   lep_charge__42->GetXaxis()->SetTitleOffset(2);
   lep_charge__42->GetXaxis()->SetTitleFont(43);
   lep_charge__42->GetYaxis()->SetTitle(" Leptons");
   lep_charge__42->GetYaxis()->SetLabelFont(43);
   lep_charge__42->GetYaxis()->SetLabelSize(25);
   lep_charge__42->GetYaxis()->SetTitleSize(25);
   lep_charge__42->GetYaxis()->SetTitleOffset(2);
   lep_charge__42->GetYaxis()->SetTitleFont(43);
   lep_charge__42->GetZaxis()->SetLabelFont(43);
   lep_charge__42->GetZaxis()->SetLabelSize(25);
   lep_charge__42->GetZaxis()->SetTitleSize(25);
   lep_charge__42->GetZaxis()->SetTitleFont(43);
   ->Add(lep_charge,"");
   
   TH1D *lep_charge__43 = new TH1D("lep_charge__43","Lepton Charge",7,-1.75,1.75);
   lep_charge__43->SetBinContent(2,98.8972);
   lep_charge__43->SetBinContent(6,153.7622);
   lep_charge__43->SetBinError(2,2.932161);
   lep_charge__43->SetBinError(6,3.480763);
   lep_charge__43->SetEntries(4245);
   lep_charge__43->SetDirectory(0);
   lep_charge__43->SetStats(0);

   ci = TColor::GetColor("#e55934");
   lep_charge__43->SetFillColor(ci);
   lep_charge__43->SetMarkerStyle(20);
   lep_charge__43->GetXaxis()->SetTitle(" Q^{lep}");
   lep_charge__43->GetXaxis()->SetLabelFont(43);
   lep_charge__43->GetXaxis()->SetLabelSize(25);
   lep_charge__43->GetXaxis()->SetTitleSize(25);
   lep_charge__43->GetXaxis()->SetTitleOffset(2);
   lep_charge__43->GetXaxis()->SetTitleFont(43);
   lep_charge__43->GetYaxis()->SetTitle(" Leptons");
   lep_charge__43->GetYaxis()->SetLabelFont(43);
   lep_charge__43->GetYaxis()->SetLabelSize(25);
   lep_charge__43->GetYaxis()->SetTitleSize(25);
   lep_charge__43->GetYaxis()->SetTitleOffset(2);
   lep_charge__43->GetYaxis()->SetTitleFont(43);
   lep_charge__43->GetZaxis()->SetLabelFont(43);
   lep_charge__43->GetZaxis()->SetLabelSize(25);
   lep_charge__43->GetZaxis()->SetTitleSize(25);
   lep_charge__43->GetZaxis()->SetTitleFont(43);
   ->Add(lep_charge,"");
   
   TH1D *lep_charge__44 = new TH1D("lep_charge__44","Lepton Charge",7,-1.75,1.75);
   lep_charge__44->SetBinContent(2,23.1975);
   lep_charge__44->SetBinContent(6,22.19374);
   lep_charge__44->SetBinError(2,1.085081);
   lep_charge__44->SetBinError(6,1.056818);
   lep_charge__44->SetEntries(1146);
   lep_charge__44->SetDirectory(0);
   lep_charge__44->SetStats(0);

   ci = TColor::GetColor("#086788");
   lep_charge__44->SetFillColor(ci);
   lep_charge__44->SetMarkerStyle(20);
   lep_charge__44->GetXaxis()->SetTitle(" Q^{lep}");
   lep_charge__44->GetXaxis()->SetLabelFont(43);
   lep_charge__44->GetXaxis()->SetLabelSize(25);
   lep_charge__44->GetXaxis()->SetTitleSize(25);
   lep_charge__44->GetXaxis()->SetTitleOffset(2);
   lep_charge__44->GetXaxis()->SetTitleFont(43);
   lep_charge__44->GetYaxis()->SetTitle(" Leptons");
   lep_charge__44->GetYaxis()->SetLabelFont(43);
   lep_charge__44->GetYaxis()->SetLabelSize(25);
   lep_charge__44->GetYaxis()->SetTitleSize(25);
   lep_charge__44->GetYaxis()->SetTitleOffset(2);
   lep_charge__44->GetYaxis()->SetTitleFont(43);
   lep_charge__44->GetZaxis()->SetLabelFont(43);
   lep_charge__44->GetZaxis()->SetLabelSize(25);
   lep_charge__44->GetZaxis()->SetTitleSize(25);
   lep_charge__44->GetZaxis()->SetTitleFont(43);
   ->Add(lep_charge,"");
   
   TH1D *lep_charge__45 = new TH1D("lep_charge__45","Lepton Charge",7,-1.75,1.75);
   lep_charge__45->SetBinContent(2,134.9465);
   lep_charge__45->SetBinContent(6,172.8627);
   lep_charge__45->SetBinError(2,2.678105);
   lep_charge__45->SetBinError(6,3.126753);
   lep_charge__45->SetEntries(10482);
   lep_charge__45->SetDirectory(0);
   lep_charge__45->SetStats(0);

   ci = TColor::GetColor("#fde74c");
   lep_charge__45->SetFillColor(ci);
   lep_charge__45->SetMarkerStyle(20);
   lep_charge__45->GetXaxis()->SetTitle(" Q^{lep}");
   lep_charge__45->GetXaxis()->SetLabelFont(43);
   lep_charge__45->GetXaxis()->SetLabelSize(25);
   lep_charge__45->GetXaxis()->SetTitleSize(25);
   lep_charge__45->GetXaxis()->SetTitleOffset(2);
   lep_charge__45->GetXaxis()->SetTitleFont(43);
   lep_charge__45->GetYaxis()->SetTitle(" Leptons");
   lep_charge__45->GetYaxis()->SetLabelFont(43);
   lep_charge__45->GetYaxis()->SetLabelSize(25);
   lep_charge__45->GetYaxis()->SetTitleSize(25);
   lep_charge__45->GetYaxis()->SetTitleOffset(2);
   lep_charge__45->GetYaxis()->SetTitleFont(43);
   lep_charge__45->GetZaxis()->SetLabelFont(43);
   lep_charge__45->GetZaxis()->SetLabelSize(25);
   lep_charge__45->GetZaxis()->SetTitleSize(25);
   lep_charge__45->GetZaxis()->SetTitleFont(43);
   ->Add(lep_charge,"");
   
   TH1D *lep_charge__46 = new TH1D("lep_charge__46","Lepton Charge",7,-1.75,1.75);
   lep_charge__46->SetBinContent(2,3294.609);
   lep_charge__46->SetBinContent(6,3310.647);
   lep_charge__46->SetBinError(2,14.24524);
   lep_charge__46->SetBinError(6,14.27251);
   lep_charge__46->SetEntries(176187);
   lep_charge__46->SetDirectory(0);
   lep_charge__46->SetStats(0);

   ci = TColor::GetColor("#9bc53d");
   lep_charge__46->SetFillColor(ci);
   lep_charge__46->SetMarkerStyle(20);
   lep_charge__46->GetXaxis()->SetTitle(" Q^{lep}");
   lep_charge__46->GetXaxis()->SetLabelFont(43);
   lep_charge__46->GetXaxis()->SetLabelSize(25);
   lep_charge__46->GetXaxis()->SetTitleSize(25);
   lep_charge__46->GetXaxis()->SetTitleOffset(2);
   lep_charge__46->GetXaxis()->SetTitleFont(43);
   lep_charge__46->GetYaxis()->SetTitle(" Leptons");
   lep_charge__46->GetYaxis()->SetLabelFont(43);
   lep_charge__46->GetYaxis()->SetLabelSize(25);
   lep_charge__46->GetYaxis()->SetTitleSize(25);
   lep_charge__46->GetYaxis()->SetTitleOffset(2);
   lep_charge__46->GetYaxis()->SetTitleFont(43);
   lep_charge__46->GetZaxis()->SetLabelFont(43);
   lep_charge__46->GetZaxis()->SetLabelSize(25);
   lep_charge__46->GetZaxis()->SetTitleSize(25);
   lep_charge__46->GetZaxis()->SetTitleFont(43);
   ->Add(lep_charge,"");
   ->Draw("hist");
   
   TPaveText *pt = new TPaveText(0.3867634,0.9149542,0.6132366,0.97,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   TText *AText = pt->AddText("Lepton Charge");
   pt->Draw();
   
   TH1D *lep_charge__47 = new TH1D("lep_charge__47","Lepton Charge",7,-1.75,1.75);
   lep_charge__47->SetBinContent(2,3403);
   lep_charge__47->SetBinContent(6,3476);
   lep_charge__47->SetEntries(6879);
   lep_charge__47->SetDirectory(0);
   lep_charge__47->SetStats(0);
   lep_charge__47->SetMarkerStyle(20);
   lep_charge__47->GetXaxis()->SetLabelFont(43);
   lep_charge__47->GetXaxis()->SetLabelSize(25);
   lep_charge__47->GetXaxis()->SetTitleSize(25);
   lep_charge__47->GetXaxis()->SetTitleOffset(2);
   lep_charge__47->GetXaxis()->SetTitleFont(43);
   lep_charge__47->GetYaxis()->SetTitle(" Leptons");
   lep_charge__47->GetYaxis()->SetLabelFont(43);
   lep_charge__47->GetYaxis()->SetLabelSize(25);
   lep_charge__47->GetYaxis()->SetTitleSize(25);
   lep_charge__47->GetYaxis()->SetTitleOffset(2);
   lep_charge__47->GetYaxis()->SetTitleFont(43);
   lep_charge__47->GetZaxis()->SetLabelFont(43);
   lep_charge__47->GetZaxis()->SetLabelSize(25);
   lep_charge__47->GetZaxis()->SetTitleSize(25);
   lep_charge__47->GetZaxis()->SetTitleFont(43);
   lep_charge__47->Draw("Esame");
   Main->Modified();
   lep_charge->cd();
  
// ------------>Primitives in pad: Data/MC
   TPad *Data/MC = new TPad("Data/MC", "Data/MC",0,0,1,0.3);
   Data/MC->Draw();
   Data/MC->cd();
   Data/MC->Range(0,0,1,1);
   Data/MC->SetFillColor(0);
   Data/MC->SetBorderMode(0);
   Data/MC->SetBorderSize(2);
   Data/MC->SetTickx(1);
   Data/MC->SetTicky(1);
   Data/MC->SetLeftMargin(0.16);
   Data/MC->SetRightMargin(0.05);
   Data/MC->SetTopMargin(0.005);
   Data/MC->SetBottomMargin(0.3333333);
   Data/MC->SetFrameBorderMode(0);
   
   TH1D *lep_charge__48 = new TH1D("lep_charge__48","",7,-1.75,1.75);
   lep_charge__48->SetBinContent(2,0.9570193);
   lep_charge__48->SetBinContent(6,0.9485921);
   lep_charge__48->SetBinError(2,0.01688419);
   lep_charge__48->SetBinError(6,0.01655504);
   lep_charge__48->SetMinimum(0.5);
   lep_charge__48->SetMaximum(2);
   lep_charge__48->SetEntries(6494.476);
   lep_charge__48->SetDirectory(0);
   lep_charge__48->SetStats(0);
   lep_charge__48->SetMarkerStyle(20);
   lep_charge__48->GetXaxis()->SetLabelFont(43);
   lep_charge__48->GetXaxis()->SetLabelSize(25);
   lep_charge__48->GetXaxis()->SetTitleSize(25);
   lep_charge__48->GetXaxis()->SetTitleOffset(2);
   lep_charge__48->GetXaxis()->SetTitleFont(43);
   lep_charge__48->GetYaxis()->SetTitle("Data/MC");
   lep_charge__48->GetYaxis()->SetNdivisions(505);
   lep_charge__48->GetYaxis()->SetLabelFont(43);
   lep_charge__48->GetYaxis()->SetLabelSize(25);
   lep_charge__48->GetYaxis()->SetTitleSize(25);
   lep_charge__48->GetYaxis()->SetTitleOffset(2);
   lep_charge__48->GetYaxis()->SetTitleFont(43);
   lep_charge__48->GetZaxis()->SetLabelFont(43);
   lep_charge__48->GetZaxis()->SetLabelSize(25);
   lep_charge__48->GetZaxis()->SetTitleSize(25);
   lep_charge__48->GetZaxis()->SetTitleFont(43);
   lep_charge__48->Draw("");
   TLine *line = new TLine(-1.75,1,1.75,1);

   ci = TColor::GetColor("#333333");
   line->SetLineColor(ci);
   line->SetLineStyle(2);
   line->Draw();
   line = new TLine(-1.75,0.9527424,1.75,0.9527424);
   line->SetLineStyle(3);
   line->Draw();
   Data/MC->Modified();
   lep_charge->cd();
      tex = new TLatex(0.2,0.88,"ATLAS");
tex->SetNDC();
   tex->SetTextFont(72);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.3,0.88,"Open Data");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.05," Q^{lep}");
tex->SetNDC();
   tex->SetTextAlign(33);
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.75,0.69,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("lep_charge","Diboson","f");

   ci = TColor::GetColor("#fa7921");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep_charge","DrellYan","f");

   ci = TColor::GetColor("#5bc0eb");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep_charge","W","f");

   ci = TColor::GetColor("#e55934");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep_charge","Z","f");

   ci = TColor::GetColor("#086788");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep_charge","stop","f");

   ci = TColor::GetColor("#fde74c");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep_charge","ttbar","f");

   ci = TColor::GetColor("#9bc53d");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep_charge","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   lep_charge->Modified();
   lep_charge->cd();
   lep_charge->SetSelected(lep_charge);
}
